steps:
  # Build the Spring Boot backend
  - name: 'maven:3.8.4-openjdk-17'
    entrypoint: mvn
    args: ['clean', 'package', '-DskipTests']
    dir: 'Backend'
    id: 'build-backend'

  # Build and push backend container
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', '${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/backend:${COMMIT_SHA}',
      '-f', 'Backend/Dockerfile',
      'Backend'
    ]
    id: 'build-backend-image'
    waitFor: ['build-backend']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/backend:${COMMIT_SHA}']
    id: 'push-backend-image'
    waitFor: ['build-backend-image']

  # Deploy backend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [
      'run', 'deploy', 'backend',
      '--image', '${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/backend:${COMMIT_SHA}',
      '--region', '${_DEPLOY_REGION}',
      '--platform', '${_PLATFORM}',
      '--allow-unauthenticated',
            '--port', '8080',
            '--memory', '2Gi',
      # Increased CPU allocation to 2 to address observed performance bottlenecks during load testing. allocation from 1Gi to 2Gi due to higher application memory requirements observed during load testing.
      '--memory', '2Gi',
            '--timeout', '300',
      # Enable CPU throttling to reduce costs when the container is idle. '--max-instances', '10',
      '--timeout', '300',
      '--cpu-throttling',
      '--execution-environment', 'gen2'
    ]
    id: 'deploy-backend'
    waitFor: ['push-backend-image']

images:
  - '${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/backend:${COMMIT_SHA}'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
