runtime: java21
env: standard
instance_class: F1

# Environment variables are managed in Google Cloud Console
# This file is kept for local development reference only

# Optional automatic scaling settings
automatic_scaling:
  max_instances: 2
  min_instances: 0
  target_cpu_utilization: 0.65
